#!/bin/bash

theme=$(grep -Po '"'"theme"'"\s*:\s*"\K([^"]*)' /vagrant/config.json)
theme_source_path="/vagrant/public/themes/source_${theme}/"
cd $theme_source_path && node_modules/gulp/bin/gulp.js "$@"
